// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEb-oKEKeppQ9rfPMTOOEVj4fhal1by3k',
    appId: '1:672459426823:web:6f3160ae16212b680aaea2',
    messagingSenderId: '672459426823',
    projectId: 'news-1dbd1',
    authDomain: 'news-1dbd1.firebaseapp.com',
    databaseURL: 'https://news-1dbd1-default-rtdb.firebaseio.com',
    storageBucket: 'news-1dbd1.appspot.com',
    measurementId: 'G-1VVYSFK4WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAix7pd-tyy34J1kTz-hUhZX4-GWM3Cbzs',
    appId: '1:672459426823:android:c1b78da1a467d15b0aaea2',
    messagingSenderId: '672459426823',
    projectId: 'news-1dbd1',
    databaseURL: 'https://news-1dbd1-default-rtdb.firebaseio.com',
    storageBucket: 'news-1dbd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNBbDIJ3UccSVvm70aMV1XJxGsATMs0g',
    appId: '1:672459426823:ios:da664c3014d64b2a0aaea2',
    messagingSenderId: '672459426823',
    projectId: 'news-1dbd1',
    databaseURL: 'https://news-1dbd1-default-rtdb.firebaseio.com',
    storageBucket: 'news-1dbd1.appspot.com',
    iosClientId: '672459426823-8jij5uap3m3qgouqnm8r07uquue7lcem.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNBbDIJ3UccSVvm70aMV1XJxGsATMs0g',
    appId: '1:672459426823:ios:da664c3014d64b2a0aaea2',
    messagingSenderId: '672459426823',
    projectId: 'news-1dbd1',
    databaseURL: 'https://news-1dbd1-default-rtdb.firebaseio.com',
    storageBucket: 'news-1dbd1.appspot.com',
    iosClientId: '672459426823-8jij5uap3m3qgouqnm8r07uquue7lcem.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
